image: node:14
stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: $CI_REGISTRY
  SUDOSOS_BASE_TAG: sudosos/sudosos-devops/
  SUDOSOS_BACK_END: back-end
  SUDOSOS_FRONT_END: front-end
  SUDOSOS_NGINX_PROXY: nginx-proxy
  SUDOSOS_POINT_OF_SALE: point-of-sale
  VUE_APP_API_BASE: $VUE_APP_API_BASE
  VUE_APP_DEVELOP: $VUE_APP_DEVELOP
  VUE_APP_GEWIS_TOKEN: $VUE_APP_GEWIS_TOKEN
  VUE_APP_STRIPE_PUBLISHABLE_KEY: $VUE_APP_STRIPE_PUBLISHABLE_KEY

dockerize:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - apk update && apk add make
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "VUE_APP_API_BASE =$VUE_APP_API_BASE" >> .env
    - echo "VUE_APP_DEVELOP =$VUE_APP_DEVELOP" >> .env
    - echo "VUE_APP_GEWIS_TOKEN =$VUE_APP_GEWIS_TOKEN" >> .env
    - echo "VUE_APP_STRIPE_PUBLISHABLE_KEY =$VUE_APP_STRIPE_PUBLISHABLE_KEY" >> .env
    - cp ./.env ./"$SUDOSOS_BACK_END"/
  script:
    - docker build ./sudosos-"$SUDOSOS_BACK_END" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_BACK_END"
    - docker build ./sudosos-"$SUDOSOS_FRONT_END" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_FRONT_END"
    - docker build ./sudosos-"$SUDOSOS_NGINX_PROXY" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_NGINX_PROXY"
    - docker build ./sudosos-"$SUDOSOS_POINT_OF_SALE" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_POINT_OF_SALE"
    - make push-all
  environment:
    name: Development
