image: node:14
stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: $CI_REGISTRY
  SUDOSOS_BASE_TAG: sudosos/sudosos-devops/
  SUDOSOS_BACK_END: back-end
  SUDOSOS_FRONT_END: front-end
  SUDOSOS_NGINX_PROXY: nginx-proxy
  SUDOSOS_POINT_OF_SALE: point-of-sale

dockerize:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - apk update && apk add make
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # ENV variables for the back-end can be set via docker-compose.
    - cp "$ENV_FILE" ./sudosos-front-end/.env
    - cp "$ENV_FILE" ./sudosos-point-of-sale/.env
  script:
    - docker build ./sudosos-"$SUDOSOS_BACK_END" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_BACK_END"
    - docker build ./sudosos-"$SUDOSOS_FRONT_END" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_FRONT_END"
    - docker build ./sudosos-"$SUDOSOS_NGINX_PROXY" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_NGINX_PROXY"
    - docker build ./sudosos-"$SUDOSOS_POINT_OF_SALE" -t "$REGISTRY"/"$SUDOSOS_BASE_TAG""$SUDOSOS_POINT_OF_SALE"
    - make push-all
  environment:
    name: Development

dockerize-production:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - apk update && apk add make
    - docker login -u "$PROD_REGISTRY_USER" -p "PROD_REGISTRY_PASSWORD" $PROD_REGISTRY
    # ENV variables for the back-end can be set via docker-compose.
    - cp "$ENV_FILE" ./sudosos-front-end/.env
    - cp "$ENV_FILE" ./sudosos-point-of-sale/.env
  script:
    - docker build ./sudosos-"$SUDOSOS_BACK_END" -t "$PROD_REGISTRY"/sudosos/"$SUDOSOS_BACK_END"
    - docker build ./sudosos-"$SUDOSOS_FRONT_END" -t "$PROD_REGISTRY"/sudosos/"$SUDOSOS_FRONT_END"
    - docker build ./sudosos-"$SUDOSOS_NGINX_PROXY" -t "$PROD_REGISTRY"/sudosos/"$SUDOSOS_NGINX_PROXY"
    - docker build ./sudosos-"$SUDOSOS_POINT_OF_SALE" -t "$PROD_REGISTRY"/sudosos/"$SUDOSOS_POINT_OF_SALE"
    - make push-all
  environment:
    name: Production
