image: node:14
stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: $CI_REGISTRY
  VUE_APP_API_BASE: $VUE_APP_API_BASE
  VUE_APP_DEVELOP: $VUE_APP_DEVELOP
  VUE_APP_GEWIS_TOKEN: $VUE_APP_GEWIS_TOKEN
  VUE_APP_STRIPE_PUBLISHABLE_KEY: $VUE_APP_STRIPE_PUBLISHABLE_KEY

dockerize:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - apk update && apk add make
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - make build-all
    - make push-all
  environment:
    name: Development
