image: node:14
stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: $CI_REGISTRY
  SUDOSOS_BASE_TAG: sudosos/
  SUDOSOS_BACK_END: back-end
  SUDOSOS_FRONT_END: front-end
  SUDOSOS_NGINX_PROXY: nginx-proxy
  SUDOSOS_POINT_OF_SALE: point-of-sale


dockerize:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - apk update && apk add make
  script:
    - make build-all
    - make push-all
    - docker push $CI_REGISTRY/$SUDOSOS_BASE_TAG$SUDOSOS_BACK_END
    - docker push $CI_REGISTRY/$SUDOSOS_BASE_TAG$SUDOSOS_FRONT_END
    - docker push $CI_REGISTRY/$SUDOSOS_BASE_TAG$SUDOSOS_NGINX_PROXY
    - docker push $CI_REGISTRY/$SUDOSOS_BASE_TAG$SUDOSOS_POINT_OF_SALE
  except:
    - master
